### ISSUE TITLE
terraform-provider-azuread_v2.50.0_x5.exe plugin: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by hales8181** [hashicorp/terraform-provider-azuread#1399]
When replacing a azuread_privileged_access_group_eligibility_schedule the plug in crashes when trying to destroy an existing eligbility schedule, and then subsequently continues on, tries to add the schedule but fails due to the role assigniment already existing. 

`
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Could not create assignment schedule request, PrivilegedAccessGroupEligibilityScheduleRequestsClient.BaseClient.Post(): unexpected status 400 with OData error: RoleAssignmentExists: The Role assignment already exists.   
│`

Stack trace:

`Stack trace from the terraform-provider-azuread_v2.50.0_x5.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x40 pc=0xf1d6cd]

goroutine 98 [running]:
github.com/manicminer/hamilton/msgraph.(*PrivilegedAccessGroupEligibilityScheduleRequestsClient).Create(0xc00021e070, {0x1430a90, 0xc000210070}, {0xc0003e1080, {0xc000782110, 0x6}, {0x12aeefc, 0xb}, 0x0, 0x0, ...})
        github.com/manicminer/hamilton@v0.68.0/msgraph/privilegedaccess_groups_eligibilityschedule_request.go:74 +0x32d
github.com/hashicorp/terraform-provider-azuread/internal/services/identitygovernance.revokeEligibilityRequest({0x1430a90, 0xc000210070}, {0xc0003bc900, {0x14309b0, 0xc0003baba0}, 0xc00098e180, 0x0, {0x1430c50, 0x1acf5c0}}, 0xc00021e070, ...)
        github.com/hashicorp/terraform-provider-azuread/internal/services/identitygovernance/privileged_access_group_eligiblity_schedule_resource.go:294 +0x1d0
github.com/hashicorp/terraform-provider-azuread/internal/services/identitygovernance.(*PrivilegedAccessGroupEligibilityScheduleResource).Delete.PrivilegedAccessGroupEligibilityScheduleResource.Delete.func1({0x1430a90, 0xc000210070}, {0xc0003bc900, {0x14309b0, 0xc0003baba0}, 0xc00098e180, 0x0, {0x1430c50, 0x1acf5c0}})
        github.com/hashicorp/terraform-provider-azuread/internal/services/identitygovernance/privileged_access_group_eligiblity_schedule_resource.go:271 +0x315
github.com/hashicorp/terraform-provider-azuread/internal/sdk.(*ResourceWrapper).Resource.func4({0x1430a90, 0xc000210070}, 0x0?, {0x117da40?, 0xc0003bc900?})
        github.com/hashicorp/terraform-provider-azuread/internal/sdk/wrapper_resource.go:72 +0x147
github.com/hashicorp/terraform-provider-azuread/internal/sdk.(*ResourceWrapper).Resource.(*ResourceWrapper).diagnosticsWrapper.diagnosticsWrapper.func12({0x1430a90?, 0xc000210070?}, 0x0?, {0x117da40?, 0xc0003bc900?})
        github.com/hashicorp/terraform-provider-azuread/internal/sdk/wrapper_resource.go:190 +0x59
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).delete(0xc0003d5500, {0x14309e8, 0xc000458b10}, 0xd?, {0x117da40, 0xc0003bc900})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:829 +0x11b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0003d5500, {0x14309e8, 0xc000458b10}, 0xc0004c71e0, 0xc00098e100, {0x117da40, 0xc0003bc900})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:878 +0x605
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000522048, {0x14309e8?, 0xc000458a20?}, 0xc000786140)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:1060 +0xdbc
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00054a000, {0x14309e8?, 0xc000458180?}, 0xc000258070)
        github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:859 +0x56a
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1275860?, 0xc00054a000}, {0x14309e8, 0xc000458180}, 0xc000258000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:467 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002781e0, {0x14356d0, 0xc00058c340}, 0xc000790000, 0xc000510720, 0x1a6cd58, 0x0)
        google.golang.org/grpc@v1.57.1/server.go:1358 +0xe15
google.golang.org/grpc.(*Server).handleStream(0xc0002781e0, {0x14356d0, 0xc00058c340}, 0xc000790000, 0x0)
        google.golang.org/grpc@v1.57.1/server.go:1735 +0x9e7
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.57.1/server.go:970 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 39
        google.golang.org/grpc@v1.57.1/server.go:981 +0x145

Error: The terraform-provider-azuread_v2.50.0_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.`

**Comment by manicminer** [comment]
Hi @hales8181, thanks for reporting this. The provider should never crash, however looking into this it seems like this may have been most likely caused by a network or connection issue between your Terraform host and the MS Graph API. Does this happen consistently or was it just a one-off error?

**Comment by tonirvega** [comment]
> Hi @hales8181, thanks for reporting this. The provider should never crash, however looking into this it seems like this may have been most likely caused by a network or connection issue between your Terraform host and the MS Graph API. Does this happen consistently or was it just a one-off error?

I could see this error too

**Comment by EwanNoble** [comment]
Also seeing this issue in v2.53.1. This is occurring when terraform is trying to destroy an eligibility assignment that is in "Expired" state.

```
Stack trace from the terraform-provider-azuread_v2.53.1_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xb87a6d]

goroutine 54 [running]:
github.com/manicminer/hamilton/msgraph.(*PrivilegedAccessGroupEligibilityScheduleRequestsClient).Create(0xc000236e00, {0x10999d0, 0xc0002c8cb0}, {0xc00017ad60, {0xc000928638, 0x6}, {0xf1be7f, 0xb}, 0x0, 0x0, ...})
	github.com/manicminer/hamilton@v0.71.0/msgraph/privilegedaccess_groups_eligibilityschedule_request.go:74 +0x32d
github.com/hashicorp/terraform-provider-azuread/internal/services/identitygovernance.revokeEligibilityRequest({0x10999d0, 0xc0002c8cb0}, {0xc0001f8900, {0x1099880, 0xc0003f89c0}, 0xc000500700, 0x0, {0x1099b20, 0x16ff9a0}}, 0xc000236e00, ...)
	github.com/hashicorp/terraform-provider-azuread/internal/services/identitygovernance/privileged_access_group_eligiblity_schedule_resource.go:294 +0x1d0
github.com/hashicorp/terraform-provider-azuread/internal/services/identitygovernance.(*PrivilegedAccessGroupEligibilityScheduleResource).Delete.PrivilegedAccessGroupEligibilityScheduleResource.Delete.func1({0x10999d0, 0xc0002c8cb0}, {0xc0001f8900, {0x1099880, 0xc0003f89c0}, 0xc000500700, 0x0, {0x1099b20, 0x16ff9a0}})
	github.com/hashicorp/terraform-provider-azuread/internal/services/identitygovernance/privileged_access_group_eligiblity_schedule_resource.go:271 +0x315
github.com/hashicorp/terraform-provider-azuread/internal/sdk.(*ResourceWrapper).Resource.func4({0x10999d0, 0xc0002c8cb0}, 0x0?, {0xdec0e0?, 0xc0001f8900?})
	github.com/hashicorp/terraform-provider-azuread/internal/sdk/wrapper_resource.go:72 +0x147
github.com/hashicorp/terraform-provider-azuread/internal/sdk.(*ResourceWrapper).Resource.(*ResourceWrapper).diagnosticsWrapper.diagnosticsWrapper.func12({0x10999d0?, 0xc0002c8cb0?}, 0x0?, {0xdec0e0?, 0xc0001f8900?})
	github.com/hashicorp/terraform-provider-azuread/internal/sdk/wrapper_resource.go:190 +0x59
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).delete(0xc00040b500, {0x1099928, 0xc000688630}, 0xd?, {0xdec0e0, 0xc0001f8900})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:829 +0x11b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00040b500, {0x1099928, 0xc000688630}, 0xc00011d1e0, 0xc000500680, {0xdec0e0, 0xc0001f8900})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:878 +0x605
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0003f8d08, {0x1099928?, 0xc0006884e0?}, 0xc0002afdb0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:1060 +0xdbc
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0003f0820, {0x1099928?, 0xc000309c20?}, 0xc0002c8150)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:859 +0x56a
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xee2420?, 0xc0003f0820}, {0x1099928, 0xc000309c20}, 0xc0002c8070, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:467 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002bc1e0, {0x109e570, 0xc0004a3040}, 0xc000933b00, 0xc00046fe00, 0x16c1d78, 0x0)
	google.golang.org/grpc@v1.57.1/server.go:1358 +0xe15
google.golang.org/grpc.(*Server).handleStream(0xc0002bc1e0, {0x109e570, 0xc0004a3040}, 0xc000933b00, 0x0)
	google.golang.org/grpc@v1.57.1/server.go:1735 +0x9e7
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.57.1/server.go:970 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 7
	google.golang.org/grpc@v1.57.1/server.go:981 +0x145

Error: The terraform-provider-azuread_v2.53.1_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by sunevnuahs** [comment]
Also encountered the provider crashing. 

We have a number of schedules on groups and should the duration of these change the provider currently does not update these as per #1412 , so they need to be removed and then added again as a workaround.
During the apply to destroy these there was an error thrown 

_Error: retrieving Privileged Access Group Assigment Schedule ID: "6f6ca8e7-e512-4e8a-ac5e-6d08297897fd_owner_36b401a6-c0a0-4688-bb27-e657436131dc": PrivilegedAccessGroupEligibilityScheduleRequestsClient.BaseClient.Post(): unexpected status 400 with OData error: PendingRoleAssignmentRequest: There is already an existing pending Role assignment request._

(also seems there is small typo in the error message - _Assigment_ should be _Assig**n**ment_)

Despite this error during the apply, the schedule was removed, but remained in state.

The subsequent plan show the item will be destroyed:

```
Terraform will perform the following actions:

  # module.rbac_groups["itemindex"].azuread_privileged_access_group_eligibility_schedule.group_owner["dev-11111111-1111-1111-1111-111111111111"] will be destroyed
  # (because azuread_privileged_access_group_eligibility_schedule.group_owner is not in configuration)
  - resource "azuread_privileged_access_group_eligibility_schedule" "group_owner" {
      - assignment_type      = "owner" -> null
      - duration             = "P180D" -> null
      - group_id             = "00000000-0000-0000-0000-000000000000" -> null
      - id                   = "00000000-0000-0000-0000-000000000000_owner_22222222-2222-2222-2222-222222222222" -> null
      - justification        = "Group owner eligibility schedule to privileged access group by IaC" -> null
      - permanent_assignment = false -> null
      - principal_id         = "11111111-1111-1111-1111-111111111111" -> null
      - start_date           = "2024-07-23T05:51:36Z" -> null
      - status               = "Provisioned" -> null
        # (3 unchanged attributes hidden)
    }

Plan: 0 to add, 0 to change, 1 to destroy.
```

As stated above, this schedule does not exist, this was verified in the Azure portal

![image](https://github.com/user-attachments/assets/77df1a09-73b6-43e8-a4d9-31377076c368)

When applying the plan to destroy the non-existent schedule the provider crashes:


```
module.rbac_groups["itemindex"].azuread_privileged_access_group_eligibility_schedule.group_owner["dev-11111111-1111-1111-1111-111111111111"]: Destroying... [id=00000000-0000-0000-0000-000000000000_owner_22222222-2222-2222-2222-222222222222]
module.rbac_groups["itemindex"].azuread_privileged_access_group_eligibility_schedule.group_owner["dev-11111111-1111-1111-1111-111111111111"]: Still destroying... [id=00000000-0000-0000-0000-000000000000_owner_22222222-2222-2222-2222-222222222222, 10s elapsed]
(lines removed for brevity)
module.rbac_groups["itemindex"].azuread_privileged_access_group_eligibility_schedule.group_owner["dev-11111111-1111-1111-1111-111111111111"]: Still destroying... [id=00000000-0000-0000-0000-000000000000_owner_22222222-2222-2222-2222-222222222222, 2m40s elapsed]
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-azuread_v2.53.1_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xb87a6d]

goroutine 49 [running]:
github.com/manicminer/hamilton/msgraph.(*PrivilegedAccessGroupEligibilityScheduleRequestsClient).Create(0xc0000d4c40, {0x10999d0, 0xc000219110}, {0xc000297c80, {0xc000133478, 0x5}, {0xf1be7f, 0xb}, 0x0, 0x0, ...})
	github.com/manicminer/hamilton@v0.71.0/msgraph/privilegedaccess_groups_eligibilityschedule_request.go:74 +0x32d
github.com/hashicorp/terraform-provider-azuread/internal/services/identitygovernance.revokeEligibilityRequest({0x10999d0, 0xc000219110}, {0xc0000d1b00, {0x1099880, 0xc0003da9f0}, 0xc000112c80, 0x0, {0x1099b20, 0x16ff9a0}}, 0xc0000d4c40, ...)
	github.com/hashicorp/terraform-provider-azuread/internal/services/identitygovernance/privileged_access_group_eligiblity_schedule_resource.go:294 +0x1d0
github.com/hashicorp/terraform-provider-azuread/internal/services/identitygovernance.(*PrivilegedAccessGroupEligibilityScheduleResource).Delete.PrivilegedAccessGroupEligibilityScheduleResource.Delete.func1({0x10999d0, 0xc000219110}, {0xc0000d1b00, {0x1099880, 0xc0003da9f0}, 0xc000112c80, 0x0, {0x1099b20, 0x16ff9a0}})
	github.com/hashicorp/terraform-provider-azuread/internal/services/identitygovernance/privileged_access_group_eligiblity_schedule_resource.go:271 +0x315
github.com/hashicorp/terraform-provider-azuread/internal/sdk.(*ResourceWrapper).Resource.func4({0x10999d0, 0xc000219110}, 0x0?, {0xdec0e0?, 0xc0000d1b00?})
	github.com/hashicorp/terraform-provider-azuread/internal/sdk/wrapper_resource.go:72 +0x147
github.com/hashicorp/terraform-provider-azuread/internal/sdk.(*ResourceWrapper).Resource.(*ResourceWrapper).diagnosticsWrapper.diagnosticsWrapper.func12({0x10999d0?, 0xc000219110?}, 0x0?, {0xdec0e0?, 0xc0000d1b00?})
	github.com/hashicorp/terraform-provider-azuread/internal/sdk/wrapper_resource.go:190 +0x59
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).delete(0xc0003ef500, {0x1099928, 0xc0002aeb70}, 0xd?, {0xdec0e0, 0xc0000d1b00})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:829 +0x11b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0003ef500, {0x1099928, 0xc0002aeb70}, 0xc00046f5f0, 0xc000112c00, {0xdec0e0, 0xc0000d1b00})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:878 +0x605

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

```

Removal of the resource instance from state resolved the issue as a workaround.
