### ISSUE TITLE
provider crash when managing a service principal resource

### ISSUE THREAD

**Issue by zoonoo** [hashicorp/terraform-provider-azuread#627]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azuread_service_principal`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

```
  # module.app.azuread_service_principal.main will be updated in-place
  ~ resource "azuread_service_principal" "main" {
        id                           = "xxxxxxx"
      ~ owners                       = [
          + "xxxxxx",
        ]
        tags                         = []
        # (16 unchanged attributes hidden)
    }
```

### Actual Behavior

```
│ Error: Plugin did not respond
│ 
│   with module.app.azuread_service_principal.main,
│   on .terraform/modules/app/main.tf line 6, in resource "azuread_service_principal" "main":
│    6: resource "azuread_service_principal" "main" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-azuread_v2.0.1_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1766e27]

goroutine 47 [running]:
github.com/manicminer/hamilton/msgraph.(*ServicePrincipalsClient).AddOwners(0xc0000a6980, 0x1e9e678, 0xc0007d3020, 0xc0002f9618, 0x1, 0xc0006be6a8, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azuread/vendor/github.com/manicminer/hamilton/msgraph/serviceprincipals.go:272 +0xa7
github.com/hashicorp/terraform-provider-azuread/internal/services/serviceprincipals.servicePrincipalResourceUpdate(0x1e9e678, 0xc0007d3020, 0xc0000a7600, 0x1b57680, 0xc0000c6000, 0xc0003e8f20, 0x16c9eea, 0xc0000a1a00)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azuread/internal/services/serviceprincipals/service_principal_resource.go:409 +0x13c9
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc000898d20, 0x1e9e608, 0xc0000a2640, 0xc0000a7600, 0x1b57680, 0xc0000c6000, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azuread/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:364 +0x17f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000898d20, 0x1e9e608, 0xc0000a2640, 0xc0003421c0, 0xc0000a1a00, 0x1b57680, 0xc0000c6000, 0x0, 0x0, 0x0, ...)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azuread/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:464 +0x390
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0002840c0, 0x1e9e608, 0xc0000a2640, 0xc0000fcaa0, 0xc0000a2640, 0x1c5b1e0, 0xc0000f5c00)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azuread/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:955 +0x8ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc0000a1580, 0x1e9e6b0, 0xc0000a2640, 0xc000342000, 0xc0000a1580, 0xc0000f5ce0, 0xc0005d7ba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azuread/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1c5b1e0, 0xc0000a1580, 0x1e9e6b0, 0xc0000f5ce0, 0xc0007d2360, 0x0, 0x1e9e6b0, 0xc0000f5ce0, 0xc000171800, 0x7f9)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azuread/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001ffc00, 0x1ea8438, 0xc00008b800, 0xc0000ccd80, 0xc00056ea50, 0x2468980, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azuread/vendor/google.golang.org/grpc/server.go:1217 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0001ffc00, 0x1ea8438, 0xc00008b800, 0xc0000ccd80, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azuread/vendor/google.golang.org/grpc/server.go:1540 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00009a490, 0xc0001ffc00, 0x1ea8438, 0xc00008b800, 0xc0000ccd80)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azuread/vendor/google.golang.org/grpc/server.go:878 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azuread/vendor/google.golang.org/grpc/server.go:876 +0x1fd

Error: The terraform-provider-azuread_v2.0.1_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by manicminer** [comment]
Thanks again for reporting this crash. I'm going to take no news as being good news and tentatively close this issue as resolved in v2.6.0. If this isn't the case, please let me know and I'll be happy to reopen the issue for further investigation. Thanks!
